#!/usr/bin/env node
/**
 * Generates a VAPID keypair for Web Push.
 *
 * The standard `web-push` CLI would do this too, but that package does not run on
 * Workers (it calls crypto.createECDH), so keeping generation here avoids installing a
 * dependency we can never use at runtime.
 *
 * The private key is written to relay/.dev.vars (gitignored) rather than printed, so it
 * does not end up in a terminal scrollback or a shared transcript. Only the public key
 * is echoed — that one is meant to be public and ships inside the extension.
 *
 *   node scripts/generate-vapid.mjs
 */
import { webcrypto } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const devVars = resolve(here, "../.dev.vars");

if (existsSync(devVars) && !process.argv.includes("--force")) {
  console.error(`Refusing to overwrite ${devVars}.`);
  console.error("Existing keys would be lost and every paired browser would break.");
  console.error("Pass --force if you really mean to rotate them.");
  process.exit(1);
}

const b64u = (buf) => Buffer.from(buf).toString("base64url");

// VAPID signs with ECDSA over P-256 (RFC 8292).
const pair = await webcrypto.subtle.generateKey({ name: "ECDSA", namedCurve: "P-256" }, true, [
  "sign",
  "verify",
]);

const publicKey = b64u(await webcrypto.subtle.exportKey("raw", pair.publicKey));
const { d: privateKey } = await webcrypto.subtle.exportKey("jwk", pair.privateKey);

const subject =
  readFileSync(resolve(here, "../wrangler.toml"), "utf8").match(
    /VAPID_SUBJECT\s*=\s*"([^"]+)"/,
  )?.[1] ?? "mailto:you@example.com";

writeFileSync(
  devVars,
  `# Generated by scripts/generate-vapid.mjs. Gitignored. Do not commit or paste anywhere.
VAPID_SUBJECT="${subject}"
VAPID_PUBLIC_KEY="${publicKey}"
VAPID_PRIVATE_KEY="${privateKey}"
`,
  { mode: 0o600 },
);

console.log("Wrote relay/.dev.vars (private key stays in that file).\n");
console.log("Public key — put this in extension/.env as WXT_VAPID_PUBLIC_KEY:\n");
console.log(publicKey);
console.log("\nNext: upload both keys as Worker secrets, e.g.");
console.log("  npx wrangler secret put VAPID_PUBLIC_KEY");
console.log("  npx wrangler secret put VAPID_PRIVATE_KEY");
